name: GitHub Actions Demo
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
  push:
    branches: [main]
    paths-ignore: [.github/**]
  schedule:
    - cron: "15 06 * * SUN"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Print event that triggered me
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - name: Check me out
      - uses: actions/checkout@v4

      - name: List files in repo
      - run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
