name: matrixmebaby
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
  pull_request:
    branches:
    - main
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  schedule:
    - cron: "15 06 * * SUN"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Print event that triggered me
        run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - name: Check me out
        uses: actions/checkout@v4

      - name: List files in repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event == 'workflow_dispatch'
    environment: Test

    steps:
      - run: echo 'Testing!'

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event == 'workflow_dispatch'
    environment: Load-Test
    
    steps:
      - run: echo 'Testing...' ; sleep 5

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: github.event.inputs.environment == 'Production'
    environment:
      name: Production
      url: https://writeabout.net
    
    steps:
      - run: |
          echo "🚀 Step 1..."
          sleep 3
      - run: |
          echo "🚀 Step 2..."
          sleep 3
      - run: |
          echo "🚀 Step 3..."
          sleep 3
      - run: |
          echo "🚀 Step 4..."
          sleep 3
      - run: |
          echo "🚀 Step 5..."
          sleep 3
